# Re-uses the secret from the Github Webhook plugin
unclassified:
  generic-webhook-trigger:
    whitelist:
      enabled: true
      whitelistItems:
      - hmacAlgorithm: HmacSHA256
        hmacCredentialId: github-webhook-shared-secret
        hmacEnabled: true
        hmacHeader: x-hub-signature-256
